### ISSUE TITLE
accountsservice - which way to go?

### ISSUE THREAD

**Issue by tari01** [AyatanaIndicators/ayatana-indicator-keyboard#1]
This is not a bug report, please label it as a discussion.

The keyboard indicator is the last one in the Ayatana series, and the only one that does not build on Non-Buntu systems due to its dependency on the accountsservice package heavily patched by Canonical.
I have had a good look at the source and don't really see which is the best direction to take:

1. If we distribute a patched accountsservice it would constantly need to be versioned above the official package
2. We could distribute an ayatana-accountsservice that would "provide" the original, but it would always need to be synchronized with the latest official package
3. Distribute some sort of diff libraries that hook into the official accountsservice package and provide the needed functionality (heavy rocket science)
4. Rewrite the vala code to get the functionality from other available libs
5. Something else?

My personal favourite is No. 2, being the easiest, but it would need a dedicated maintainer.

**Comment by sunweaver** [comment]
Hi,

On  So 10 Mär 2019 17:48:23 CET, Robert Tari wrote:

> This is not a bug report, please label it as a discussion.
>
> The keyboard indicator is the last one in the Ayatana series, and  
> the only one that does not build on Non-Buntu systems due to its  
> dependency on the accountsservice package heavily patched by  
> Canonical.
> I have had a good look at the source and don't really see which is  
> the best direction to take:
>
> 1. If we distribute a patched accountsservice it would constantly  
> need to be versioned above the official package
> 2. We could distribute an ayatana-accountsservice that would  
> "provide" the original, but it would always need to be synchronized  
> with the latest official package
> 3. Distribute some sort of diff libraries that hook into the  
> official accountsservice package and provide the needed  
> functionality (heavy rocket science)
> 4. Rewrite the vala code to get the functionality from other available libs
> 5. Something else?
>
> My personal favourite is No. 2, being the easiest, but it would need  
> a dedicated maintainer.

sorry for not having picked up this initiative approach earlier.

I have a comm backlog from a year ago with Robert Ancell. I need to  
dig it out and refurbish the info so that it becomes appropriate for  
sharing here.

It will be about the relation of the keyboard system indicator and  
accountsservice.

So, stay tuned... (April...).

Mike
-- 

DAS-NETZWERKTEAM
c\o Technik- und Ökologiezentrum Eckernförde
Mike Gabriel, Marienthaler str. 17, 24340 Eckernförde
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by sunweaver** [comment]
Here comes the long promised info from Robert Ancell:

Some background on this:

Back when we designed Unity Greeter it drove some requirements to store
some shared information about users. We decided to add this into
AccountsService (which already contained similar information). Upstream
decided (fairly) that adding arbitrary amounts of data to AccountsService
was a bad idea, and discussions concluded on there should be an extension
mechanism to allow this. As we had more requirements to add information for
Ubuntu Phone the extension mechanism was added. I intended to migrate
LightDM over, but it always seemed too difficult / low priority. Once we
switched to GNOME in Ubuntu I felt it was time to do a quick-and-dirty
switch so LightDM would work better on other desktops.

The commits in LightDM are:
https://github.com/CanonicalLtd/lightdm/commit/6015bce25f241e7580c03594d846769f8236232f
https://github.com/CanonicalLtd/lightdm/commit/f57919df4f00656c800ffad8a3ba41e3b27ba776

I don't know of any documentation for AccountsService - I just coped other
projects that were using this feature.

So indicator-keyboard would need a similar patch to LightDM.

**Comment by sunweaver** [comment]
The relevant commits in AccountsService are:
https://cgit.freedesktop.org/accountsservice/commit/?id=21de4bd55fdfd8e34295351666ab2fac71ac94d2
https://cgit.freedesktop.org/accountsservice/commit/?id=a21ec621277cb8ee07b44d5d3d397b153a7f7d21

**Comment by sunweaver** [comment]
@mariogrip: is the keyboard indicator used in Ubuntu Touch? Is Unity Greeter still used in Ubuntu Touch? Or some other greeter that requires cross-account (display manager -> user session) communication of indicator settings (keyboard, sound, etc.)?

**Comment by tari01** [comment]
Resolved, closing.
