### ISSUE TITLE
ayatana-indicator-keyboard always crashes on system/session start

### ISSUE THREAD

**Issue by flexiondotorg** [AyatanaIndicators/ayatana-indicator-keyboard#5]
There are multiple reports that ayatana-indicator-keyboard-service crashed with SIGSEGV in keyboard_GetLayout() Edit

These reports come from testers of Ubuntu MATE 21.04. We have introduced ayatana-indicator-keyboard for the first time in the release, which is due for final release at the end of April.

Here is the downstream bug report which includes backtraces and logs:

  * https://pad.lv/1915492

`StacktrackSource.txt` attached to the downstream bug might be useful:

  * https://launchpadlibrarian.net/522595152/StacktraceSource.txt

**Comment by tari01** [comment]
@flexiondotorg 

The remedy is out.

A bit of a curiousity: On Manjaro all layouts are at the same time variants, while Ubuntu has certain layouts that have no variant info at all. One would think these things are the same everywhere.

On my end, the US layout is
**LANGUAGE = en
VARIANT = us**
On Ubuntu, however
**LANGUAGE = us
VARIANT = null**

Lucky for us, libxklavier is smart enough to sort this out :)

**Comment by N0rbert** [comment]
I applied the patch locally, it works as expected. Thank you!

**Comment by tari01** [comment]
@N0rbert 

This indicator does not yet have a mechanism for peeking into a user account, so it will fail when trying to get the user's layout list. I would not use it at login time until we make it smarter.

**Comment by flexiondotorg** [comment]
I confirm that this first the crash on session start for the user.

  * I've submitted the patch to Debian packaging for `ayatana-indicator-keyboard` @sunweaver 
  * I've uploaded a patched version of `ayatana-indicator-keyboard` to Ubuntu 21.04 archive.

To work around the crash in lightdm I have removed the keyboard indicator from the Arctica Greeter settings.
