### ISSUE TITLE
Request for feature: Show Current keyboard Layout

### ISSUE THREAD

**Issue by N0rbert** [AyatanaIndicators/ayatana-indicator-keyboard#7]
As long time Ubuntu MATE user I expect that keyboard indicator has the Show Current keyboard Layout functionality. 
It is very useful for reminding the location of third-level typographic characters.

The below screenshot indicates this functionality with current MATE Control Center on  Ubuntu MATE 21.04 daily:

![mcc-scl](https://user-images.githubusercontent.com/309456/113289660-29290c00-92f9-11eb-8a29-27d0ce81908c.png)

If it is possible please implement the above functionality in `ayatana-indicator-keyboard`.

**Comment by sunweaver** [comment]
@N0rbert Where is that menu item coming from? I just checked the Ubuntu indicator-keyboard (the version, that UBports uses), but I can't find the Show Current Layout menu item. What keyboard icon are you using in the above image? Ideally, please also provide the code project where to find the implementation.

I have, btw, discovered that libgnomekbd-common has a show-layout.ui GTK layout for this:
/usr/share/libgnomekbd/ui/show-layout.ui

Is your screenshot internally using that?



I have checked lib

**Comment by N0rbert** [comment]
It is default MATE keyboard applet. For current keyboard layout see https://github.com/mate-desktop/mate-settings-daemon/blob/a5a9306239a616979d726c840c5a1fa7ef944053/plugins/keyboard/msd-keyboard-xkb.c#L298 .

Thanks.
