### ISSUE TITLE
Request for feature: show current keyboard layout as country flag

### ISSUE THREAD

**Issue by N0rbert** [AyatanaIndicators/ayatana-indicator-keyboard#8]
As long time Ubuntu MATE user I expect that keyboard indicator can indicate current keyboard layout as country flag.
Currently default MATE keyboard indicator allows one to have the country flag after setting the following setting:

```
gsettings set org.mate.peripherals-keyboard-xkb.indicator show-flags true
```

The below screenshot indicates this functionality with current MATE Control Center on Ubuntu MATE 21.04 daily:

![mcc-k-menu](https://user-images.githubusercontent.com/309456/113290115-d865e300-92f9-11eb-91bb-dcbfa52c8582.png)

If it is possible please implement the above functionality in ayatana-indicator-keyboard.

**Comment by sunweaver** [comment]
@N0rbert: any idea where the code for the default MATE keyboard indicator (the one you used for your screenshot) resides? That would be helpful for porting that functionality over.

**Comment by N0rbert** [comment]
It is default MATE keyboard applet. For flag see https://github.com/mate-desktop/libmatekbd/blob/01ff58dfc264ccaf7d8cabf42d6e8e6229ae5d21/libmatekbd/matekbd-indicator-config.c#L42 .

**Comment by tari01** [comment]
@N0rbert @sunweaver 

Unfortunately we cannot implement this. The Ayatana keyboard indicator uses a very different approach from MATE keyboard indicator: we are strictly indicating languages, not countries (see https://github.com/AyatanaIndicators/ayatana-indicator-keyboard/issues/9). One may choose one layout, but reside in a completely different country, which would raise all sort of inappropriate behaviour...

Closing, thus.
