### ISSUE TITLE
Ayatana-indicator-keyboard has inconsistent button label for layouts

### ISSUE THREAD

**Issue by saivinob** [AyatanaIndicators/ayatana-indicator-keyboard#9]
I have enabled 3 layouts: English (US) default and other two local languages. When I click on the indicator, for English it shows 'En' the language code, whereas for the local languages, it shows 'In' the country code. It should be consistent; either all should be country code (problematic for multiple languages from same country) or preferably should show language code. Hope the screenshot will make it clear.

![Screenshot_at_2021-04-01_21-53-43](https://user-images.githubusercontent.com/54169365/113471869-e3954c00-947c-11eb-9536-e030cbaa6686.png)

**Comment by sunweaver** [comment]
@tari01 can you possible look at this? I sense that we should rather use the language code (and maybe put the country code in the menu item's text). What do you think?

**Comment by tari01** [comment]
> @tari01 can you possibly look at this? I sense that we should rather use the language code (and maybe put the country code in the menu item's text). What do you think?

Yes, language code definitely. I wrote the icon generator correctly (It gives **Sa** and **Ka** for the last two menu items), but I probably messed up something in the indicator. Will check, of course.
